version: "3"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
      target: database
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: todos
      TZ: Asia/Tokyo
    restart: always

volumes:
  pgdata:
